# Generated by Django 5.2.4 on 2025-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_mobile_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.FloatField(default=0),
        ),
    ]
